services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Admin12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - hotelnet
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Admin12345",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  hotelapi:
    build: .
    container_name: hotelapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Server=sqlserver;User Id=sa;Password=Admin12345;Database=Hotel-API;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - hotelnet

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - hotelnet

networks:
  hotelnet:

volumes:
  sqlserverdata:
